# Generated by Django 4.2 on 2023-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото профиля')),
                ('text', models.CharField(max_length=200, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв пользователя',
                'verbose_name_plural': 'Отзыв пользователя',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('number', models.CharField(max_length=200, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('full_name_en', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка сотрудника')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('position_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
